### ISSUE TITLE
[feature request] adding max_width for lsp_signature_help

### ISSUE THREAD

**Issue by bassamsdata** [deathbeam/autocomplete.nvim#1]
Thank you for the plugin.

I've noticed that sometimes the floating window becomes too wide (see below). I was wondering if it's possible to consider adding a max_width option for lsp_signature_help. I'd be happy to make a PR if you're open to it.

Thanks!

<img width="1667" alt="Screenshot 2024-02-16 at 11 26 16 PM" src="https://github.com/deathbeam/autocomplete.nvim/assets/105807570/25d407ba-999c-420d-96a7-50a5a4fccf3f">

**Comment by deathbeam** [comment]
Yea good idea. Looks like its an option for `open_floating_preview` im using, so simple enough to add. If you want to make PR then sure, I guess it should also be configurable

**Comment by bassamsdata** [comment]
thank you, apologies, I wasn't in front of my computer the whole day to implement it.
